### ISSUE TITLE
issue 불필요 코드 삭제.

### ISSUE THREAD

**Issue by Gamza-park** [AisMobileTeam/ais_mobile_chatApp#118]
기능 추가 요구 사항 : FriendsListAdapter -> FragFriend 로 옮겨지며 불필요해진 코드 제거.

**Comment by yang960701** [comment]
수고 많으셨습니다.
지금 친구 추가 할때 요청까지는 정상적으로 들어오는데 2명 이상 요청이 들어오면 1명일때 로그인 화면으로 팅기고 또 1명 들어올때 아예 앱이 꺼지는 이슈가 확인중인데  확인부탁드릴 수 있을까요?

**Comment by Gamza-park** [comment]
> 수고 많으셨습니다.
> 지금 친구 추가 할때 요청까지는 정상적으로 들어오는데 2명 이상 요청이 들어오면 1명일때 로그인 화면으로 팅기고 또 1명 들어올때 아예 앱이 꺼지는 이슈가 확인중인데 확인부탁드릴 수 있을까요? 꺼진 다음에 들어가보면 친구 추가는 되어 있습니다.


> 수고 많으셨습니다.
> 지금 친구 추가 할때 요청까지는 정상적으로 들어오는데 2명 이상 요청이 들어오면 1명일때 로그인 화면으로 팅기고 또 1명 들어올때 아예 앱이 꺼지는 이슈가 비정기적으로 발생하는데 확인부탁드릴 수 있을까요?
> 꺼진 다음에 들어가보면 친구 추가는 되어 있습니다.

이슈하나 등록해놔주시면 그거로 해서 작업 시작하겟습니다.
일단 오류는 확인 했습니다.
